
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { resolve } from "path";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment variables from .env.local first (Next.js pattern)
// Use absolute path resolution for reliability
const envLocalPath = resolve(process.cwd(), ".env.local");
const envPath = resolve(process.cwd(), ".env");

const result1 = config({ path: envLocalPath });
const result2 = config({ path: envPath });

// Debug: show what keys were loaded
const loadedKeys1 = result1.parsed ? Object.keys(result1.parsed) : [];
const loadedKeys2 = result2.parsed ? Object.keys(result2.parsed) : [];
console.error("Keys from .env.local:", loadedKeys1.join(", ") || "none");
console.error("Keys from .env:", loadedKeys2.join(", ") || "none");
console.error("DATABASE_URL present:", !!process.env.DATABASE_URL);

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is required. Make sure your .env.local file contains DATABASE_URL.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
    // DIRECT_URL is optional for local dev, required for Vercel Postgres pooling
    directUrl: process.env.DIRECT_URL || undefined,
  },
});
