
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Load environment variables from .env.local first (Next.js pattern)
config({ path: ".env.local" });
// Fallback to .env
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
    // DIRECT_URL is optional for local dev, required for Vercel Postgres pooling
    directUrl: process.env.DIRECT_URL || undefined,
  },
});
